### PR TITLE
Add handling of variable imports and exports.

### PR DESCRIPTION
**Pull request by bythos14**
Also added known fields in SceModuleInfo. See: https://github.com/vitasdk/vita-toolchain/blob/master/src/sce-elf-defs.h#L33-L35

### CODE REVIEW

**Comment by bythos14** [comment]
Would you happen to know a way to set the name of the variables without creating a label?

**Comment by xerpi** [comment]
> Would you happen to know a way to set the name of the variables without creating a label?

I don't actually :(. I guess we'll have to take a look at Ghidra's API.

**Comment by xerpi** [comment]
Is this the latest version? If so, I'll merge it, thanks for adding variable imports/exports support!

**Comment by bythos14** [comment]
Could you perhaps wait a few minutes before merging it? I'm working on having the script name known common NIDs for modules. And I also want to define the SceProcessParam structure.

**Comment by bythos14** [comment]
NIDs like the one for module_start and SceProcessParam, etc

**Comment by bythos14** [comment]
That took far longer than expected. You should be good to merge now.

**Comment by xerpi** [comment]
Perfect, thanks!

**Pull request merged**
